### ISSUE TITLE
Unable to install in 3.1.2

### ISSUE THREAD

**Issue by KBCase** [stefanwalther/sense-media-box#11]
Stefan,

There seems to be an issue installing the extension in server version 3.1.2.  Error is 

5c98dbdc-32db-42e7-8a8d-136300c1594a	EHL\qlik	Request failed: file not found /extensions/swr-mediabox/lib/css/main.css			627a6c8c-80ec-42cf-88a9-c19c9b2479cc	5c98dbdc-32db-42e7-8a8d-136300c1594a
226	20170630T091434.704-0400	ERROR	Qlik-Dev	System.Repository.Repository.Core.Repository.Common.TransactionUtility	30	793459ff-207a-49ee-8d67-ce8a894cd397	EHL\qlik	Error when committing.	Duplicate extension (the extension already exists or occurs more than once in the ZIP file): swr-mediabox	   at Repository.Core.Resource.Support.ExtensionResourceSupport.<>c__DisplayClass20_0.<CreateExtension>b__0()↵↓   at Repository.Core.Repository.Common.TransactionUtility.RunInTransaction(ITransaction transaction, IEnumerable`1 actions)	627a6c8c-80ec-42cf-88a9-c19c9b2479cc	793459ff-207a-49ee-8d67-ce8a894cd397
227	20170630T091434.704-0400	INFO	Qlik-Dev	System.Repository.Repository.Core.Resource.Support.ExtensionResourceSupport	30	9e179fdd-4f9a-43d9-a77d-9017eba17b99	EHL\qlik	Failed to add extension 	Duplicate extension (the extension already exists or occurs more than once in the ZIP file): swr-mediabox	   at Repository.Core.Resource.Support.ExtensionResourceSupport.<>c__DisplayClass20_0.<CreateExtension>b__0()↵↓   at Repository.Core.Repository.Common.TransactionUtility.RunInTransaction(ITransaction transaction, IEnumerable`1 actions)↵↓   at Repository.Core.Repository.Common.TransactionUtility.RunInTransaction(Action[] actions)↵↓   at Repository.Core.Resource.Support.ExtensionResourceSupport.CreateExtension(String extensionName, Boolean appendPrivileges, List`1 installedExtensions, String sourceDirectory, Boolean sourceIsZip, Guid extensionId)↵↓   at Repository.Core.Resource.Support.ExtensionResourceSupport.Add(String path, String password, Boolean appendPrivileges)	627a6c8c-80ec-42cf-88a9-c19c9b2479cc	9e179fdd-4f9a-43d9-a77d-9017eba17b99

Thanks.

Kevin

**Comment by stefanwalther** [comment]
I guess you are installing the entire GitHub repo instead of just installing one very version of sense-media-box?!
Download one of the .zip files in https://github.com/stefanwalther/sense-media-box/tree/master/build and then you should be fine!

**Comment by KBCase** [comment]
Stefan,

Thanks!  That worked.
