### ISSUE TITLE
Content disappears when in full screen mode

### ISSUE THREAD

**Issue by fkabinoff** [stefanwalther/sense-media-box#12]
If the object is in fullscreen mode, the content disappears. This appears to be related to class .qv-object.qvt-visualization.qv-layout-full having a width set to 0 by the Qlik Sense client CSS, and relying on flex to size it, while the .qv-object-swr-mediabox class styling overrides the position: relative of .qv-object with position: absolute, which causes the flex not to work.

**Comment by stefanwalther** [comment]
... weird stuff ... I'll investigate ... ;-)
