### ISSUE TITLE
Unable to install on Qlik Sense Server

### ISSUE THREAD

**Issue by simonjzf** [stefanwalther/sense-media-box#18]
Server version:Qlik Sense 3.2 SR4

I follow steps as below:
1.Select Extensions on the QMC start page or from the Start drop-down menu to display the overview.
2.Click  Import in the action bar.
3.The Import extension file dialog opens. Select a zip file to import.
   Remember to enter the password for the zip file if it is password protected.
4.Click Open in the file explorer window.
5.Click Import.

it return the error message in the %ProgramData%Qlik/Sense/Log/Repository/System/<machine ID>_Service_Repository.txt:

`Sequence#	ProductVersion	Timestamp	Severity	Hostname	Id	Description	ProxySessionId	ProxyPackageId	RequestSequenceId	UserDirectory	UserId	ObjectId	ObjectName	Service	Origin	Context	Command	Result	Message	Id2
24	12.22.6.0	20171114T150158.405+0800	ERROR	CNIHKBI1	c7050292-174c-48af-b7d2-e72b8731a7ce	Command=Add extension;Result=400;ResultText=Error: PersistenceFailed	add34056-522b-4d08-9ab2-ae8b7f8c7c3d	904d97c2-790f-4a61-aa9c-4e9eb7a814f3	0	CNIHKBI1	qlik01	0	Not available	Repository	ManagementAccess	/qrs/extension/upload	Add extension	400	 Cannot add the following file: initialproperties.js. There might be a problem accessing it. (HTTP code: 400)	c7050292-174c-48af-b7d2-e72b8731a7ce
`

please help me. thanks a lot.

**Comment by stefanwalther** [comment]
Sorry for the delayed answer.
Can it be, that you have downloaded the entire GitHub repository (download button on the main page of the GitHub repository) instead of downloading one of the .zip file from https://github.com/stefanwalther/sense-media-box/tree/master/build

**Comment by stefanwalther** [comment]
Follow the instructions here, hope this helps: https://github.com/stefanwalther/sense-extension-install
