### ISSUE TITLE
Vertical Align

### ISSUE THREAD

**Issue by mathiasfrohlich** [stefanwalther/sense-media-box#2]
Need it to be able to align vertically. Can this happen or please direct me to where i can implement this.

**Comment by stefanwalther** [comment]
Shouldn't be that hard ... probably in `src/lib/less/main.less` ... Any PR is highly appreciated, otherwise I'll try to have a look at it as soon as possible ...

**Comment by stefanwalther** [comment]
Fixed with version 0.3.0, just released.
