### ISSUE TITLE
Where i can get Docker images qlik/engine and qlik/sense-client ?

### ISSUE THREAD

**Issue by Slach** [stefanwalther/sense-media-box#20]
sorry for my offtopic
As i see hear
https://github.com/stefanwalther/sense-media-box/blob/master/docker-compose.yml#L9
do you have private repository for qlik/egine and qlik/sense-client docker image?
Could you explain me where i can get these images?
https://hub.docker.com/r/qlik/ don't have public qlik/engine image ;(

**Comment by stefanwalther** [comment]
I am sorry for the confusion, this happened by mistake ... (gitignore did not work correctly).
