### ISSUE TITLE
Invalid visualization error in QlikSense Desktop 2017 Patch 2 

### ISSUE THREAD

**Issue by aniletnirmal** [stefanwalther/sense-media-box#25]
Hi Stefan, 
I installed the latest version of sense-media-box extension available in QlikBranch in QlikSense Desktop 2017 Patch 2. 

While trying to use in the app, it shows the following error.

![mediabox-invalid viz- qliksense desktop](https://user-images.githubusercontent.com/35177446/36786677-b6625496-1ca0-11e8-98b2-d944f519447c.png)

* Extension version: latest version available on QlikBranch
* Browser: NA
* Qlik Sense Desktop: 2017 Patch 2
* Qlik Sense Enterprise: NA
* Operating system: Windows
* [Other relevant versions] NA

**Comment by stefanwalther** [comment]
Hi, can it be that you ran into the following problem?

https://github.com/stefanwalther/sense-extension-install#i-am-getting-an-error-uploading-the-extension-to-qlik-sense-server-what-can-i-do

I hope this helps, let me know.

**Comment by aniletnirmal** [comment]
I followed the steps, its working now. 

Thank you.

Regards,
Anilet Nirmal
