### ISSUE TITLE
URL for images in QMC content libraries

### ISSUE THREAD

**Issue by jjacksonava** [stefanwalther/sense-media-box#4]
Hi Stefan, 

Thanks for the great Mediabox extension for Qlik Sense, it has been very helpful in our project! 

Just something that came up, we had a bit of trouble accessing images stored in the QMC content repository, as we couldn’t find the url to point to. Turns out, this url is located within the qmc content repository itself (who would have thought!). 

It may be helpful for future users to have this note on the readme, as it isn’t initially clear, but ill leave that in your capable hands. 

Many thanks once again, 

Jack

**Comment by stefanwalther** [comment]
@jjacksonava Is this still an issue for you?
(just in the process of cleaning up issues right now)

**Comment by jjacksonava** [comment]
Hi Stefan, wow this was a while back!
Not an issue anymore, I think we found a workaround at the time.
Many Thanks,
Jack

**Comment by stefanwalther** [comment]
Thx.
