### ISSUE TITLE
Maximum Length HTML

### ISSUE THREAD

**Issue by EJdK** [stefanwalther/sense-media-box#6]
Hi Stefan,

Is there a maximum length for the HTML code you can enter? I am unable to enter more characters after a while. 

And if so, is there a way around it for example by loading the HTML in the load script and add it as a variable or some other way?

Thanks, Erik

**Comment by stefanwalther** [comment]
Hi, I haven't really tested. If I can recall it correctly there is a limit on the length the engine can store, but I will double-check and come back.

**Comment by stefanwalther** [comment]
I have tested several times, do not see an issue with very, very long strings.
So closing this for now, as long as you still have the issue and want to re-open.
