### ISSUE TITLE
Multiple Images on the dashboard

### ISSUE THREAD

**Issue by Riya-Agarwal** [stefanwalther/sense-media-box#7]
Hi Stefan,

I am trying to pull multiple images on the media box via URL. It shows up the same image in each box. I want to select multiple images in the filters.

Is this possible?

Thanks,
Riya

**Comment by stefanwalther** [comment]
No, currently not supported, but any PR is highly welcome.

**Comment by stefanwalther** [comment]
Closing this feature request, as it is not an issue of the extension.
