### ISSUE TITLE
Implement .css with HTML link

### ISSUE THREAD

**Issue by Insightsintelligence** [stefanwalther/sense-media-box#9]
Hi, 

Very nice extension, always did the trick for me. I use the 'website' link and then input a path to any html on my drive/server. However, when I want to add .css or .xml compatability it doesn't work on the server (because I can't go one folder 'deeper' in the content folder of the server). My question is, whether or not it is possible to make HTML with .CSS files work on the server? (it is possible in Qlik Sense Desktop). 

With kind regards,

Remco de Bruijn

**Comment by stefanwalther** [comment]
Hi @Insightsintelligence, this is nothing I am planning right now. Feel free to file a PR, but other than that, I am closing this feature request for now.
